### ISSUE TITLE
Set site page structure

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/docs-theme#18]

**Comment by daremiyo** [comment]
I think I got the right directory structure in place - still need to resolve 2 things that happened because of the new page structure for the processing manual items: 

1) the top navbar brought in the processing-manual pages because of the settings on the header include 
2) the link to the processing manual on the homepage has to be changed in order to accommodate the new page structure

**Comment by HaSistrunk** [comment]
I think I resolved the two problems you noted above. Take a look at my changes in the Templates branch, and if it looks ok go ahead and close out this issue!

**Comment by daremiyo** [comment]
Looks great! I'll close the issue now
